version: "3"
services:
    #database
    mysql:
      container_name: "modxmysql"
      build: ./mysql
      ports:
        - "3306"
      volumes:
        - ./mysql/instance:/var/lib/mysql:rw
        # MySQL config
        - ./mysql/config/local.cnf:/etc/mysql/conf.d/local.cnf:ro
      env_file:
        - ./mysql/credentials.env
      command: "mysqld --sql-mode=NO_ENGINE_SUBSTITUTION --default-authentication-plugin=mysql_native_password"
    
    # php-fpm
    php:
      build: ./php-fpm
      ports:
        - "9000"
        - "9009"
      volumes:
        - ./app/src:/var/www/html:rw
        # php.ini
        - ./php-fpm/config/php.ini:/usr/local/etc/php/php.ini:ro
      env_file:
        - ./mysql/credentials.env
        - ./php-fpm/paths.env
        - ./php-fpm/modx_install.env
      depends_on:
        - mysql

    # web server
    nginx:
      container_name: "modxnginx"
      build: ./nginx
      ports:
        - "80"
        - "443"
      volumes:
        # app
        - ./app/src:/var/www/html:rw
        # nginx configs
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
        # certificates
        - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
        - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
      depends_on:
        - php

networks:
  default:
    external:
      name: dockernet