services:
  mariadb:
    container_name: "${PROJECT_NAME}_mariadb"
    image: mariadb:11.6
    ports:
      - "3306"
    restart: no
    init: true
    volumes:
      - db_data:/var/lib/mysql:rw
    env_file:
      - .env
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  php:
    container_name: "${PROJECT_NAME}_php"
    build:
      context: ./docker/php
      args:
        MODX_VERSION: "${MODX_VERSION}"
    ports:
      - "9000"
    volumes:
      - ./app/public:/var/www/html:rw
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    env_file:
      - .env
    depends_on:
      - mariadb

  nginx:
    container_name: "${PROJECT_NAME}_nginx"
    build:
      context: ./docker/nginx
    ports:
      - "${PROJECT_HTTP_PORT}:80"
      - "${PROJECT_HTTPS_PORT}:443"
    volumes:
      - ./app/public:/var/www/html:rw
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/config/site.conf:/etc/nginx/conf.d/site.conf:ro
      # certificates
      - ./docker/nginx/certs/:/etc/nginx/certs:rw
    environment:
      SERVER_NAME: "localhost"
    depends_on:
      - php

volumes:
  db_data:
