services:
    #database
    mariadb:
      container_name: "modx_db"
      build: ./mariadb
      ports:
        - "3306"
      volumes:
        - ./mariadb/instance:/var/lib/mysql:rw
        # MySQL config
        - ./mariadb/config/local.cnf:/etc/mysql/conf.d/local.cnf:ro
      env_file:
        - ./mariadb/credentials.env
      command: "mariadbd --sql-mode=NO_ENGINE_SUBSTITUTION --default-authentication-plugin=caching_sha2_password"
    
    # php-fpm
    php:
      container_name: "modx_fpm"
      build: ./php-fpm
      ports:
        - "9000"
        - "9009"
      volumes:
        - ./app/public:/var/www/html:rw
        # php.ini
        - ./php-fpm/config/php.ini:/usr/local/etc/php/php.ini:ro
      env_file:
        - ./mariadb/credentials.env
        - ./php-fpm/paths.env
        - ./php-fpm/modx_install.env
      depends_on:
        - mariadb

    # web server
    nginx:
      container_name: "modx_webserver"
      build: ./nginx
      ports:
        - "80"
        - "443"
      volumes:
        # app
        - ./app/public:/var/www/html:rw
        # nginx configs
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
        # certificates
        - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
        - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
      depends_on:
        - php
